import type { IkasProduct } from "./types";

export const sampleProducts: IkasProduct[] = [
  {
    id: "prod-001",
    name: "Minimal Gold Necklace",
    brand: { id: "brand-1", name: "Bayam" },
    vendor: { id: "vendor-1", name: "Atelier" },
    categories: [{ id: "cat-1", name: "Necklaces" }],
    tags: [{ id: "tag-1", name: "gold" }],
    description: "18k gold plated necklace.",
    shortDescription: "Everyday necklace.",
    metaData: { id: "meta-1", slug: "minimal-gold-necklace" },
    totalStock: 12,
    type: "PHYSICAL",
    deleted: false,
    variants: [
      {
        id: "var-001",
        sku: "NECK-GOLD-001",
        barcodeList: ["868000000001"],
        images: [{ imageId: "img-1", isMain: true, order: 1 }],
        isActive: true,
        sellIfOutOfStock: false,
        prices: [{ sellPrice: 1290, currencyCode: "TRY", currencySymbol: "₺" }],
        stocks: [{ id: "stock-1", productId: "prod-001", variantId: "var-001", stockLocationId: "loc-1", stockCount: 12, deleted: false }],
        deleted: false,
      },
    ],
  },
  {
    id: "prod-002",
    name: "Silver Ring",
    brand: null,
    vendor: null,
    categories: [],
    tags: [],
    description: "",
    shortDescription: null,
    metaData: { id: "meta-2", slug: "silver-ring" },
    totalStock: 0,
    type: "PHYSICAL",
    deleted: false,
    variants: [
      {
        id: "var-002",
        sku: "RING-SILVER-001",
        barcodeList: ["868000000002"],
        images: [],
        isActive: true,
        sellIfOutOfStock: false,
        prices: [{ sellPrice: 0, currencyCode: "TRY", currencySymbol: "₺" }],
        stocks: [{ id: "stock-2", productId: "prod-002", variantId: "var-002", stockLocationId: "loc-1", stockCount: 0, deleted: false }],
        deleted: false,
      },
    ],
  },
  {
    id: "prod-003",
    name: "Pearl Bracelet",
    brand: { id: "brand-2", name: "Pearl Co" },
    vendor: null,
    categories: [{ id: "cat-2", name: "Bracelets" }],
    tags: [],
    description: "Pearl bracelet.",
    shortDescription: null,
    metaData: { id: "meta-3", slug: "pearl-bracelet" },
    totalStock: 6,
    type: "PHYSICAL",
    deleted: false,
    variants: [
      {
        id: "var-003",
        sku: "RING-SILVER-001",
        barcodeList: ["868000000002"],
        images: [{ imageId: "img-3", isMain: true, order: 1 }],
        isActive: true,
        sellIfOutOfStock: true,
        prices: [{ sellPrice: 890, currencyCode: "TRY", currencySymbol: "₺" }],
        stocks: [{ id: "stock-3", productId: "prod-003", variantId: "var-003", stockLocationId: "loc-1", stockCount: 6, deleted: false }],
        deleted: false,
      },
      {
        id: "var-004",
        sku: "",
        barcodeList: [],
        images: [{ imageId: "img-4", isMain: false, order: 2 }],
        isActive: true,
        sellIfOutOfStock: false,
        prices: [{ sellPrice: 890, currencyCode: "TRY", currencySymbol: "₺" }],
        stocks: [{ id: "stock-4", productId: "prod-003", variantId: "var-004", stockLocationId: "loc-1", stockCount: 2, deleted: false }],
        deleted: false,
      },
    ],
  },
];
